---
author: ishiduca@gmail.com
description: cookie parser
devDependencies:
  qunit-tap: '~1.4.1'
  qunitjs: '~1.10.0'
keywords: cookie
license: MIT
main: ./
name: cookie-m
scripts:
  test: with-sound prove -e node --ext .js -v
version: 0.0.2
